# Generated by Django 3.0.6 on 2020-06-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0002_auto_20200627_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='native_lang',
        ),
        migrations.AddField(
            model_name='profile',
            name='lang',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
