# Generated by Django 3.0.6 on 2020-06-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0003_auto_20200629_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lang',
        ),
    ]
