# Generated by Django 3.0.6 on 2020-06-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0004_remove_profile_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='from_lang',
        ),
        migrations.RemoveField(
            model_name='article',
            name='to_lang',
        ),
    ]
