# Generated by Django 3.0.6 on 2020-07-01 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0007_auto_20200630_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='idiom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='word',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='WordIdiomTable',
        ),
    ]
