# Generated by Django 3.0.6 on 2020-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0009_auto_20200701_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='origin_sentence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='translated_sentence',
            field=models.TextField(),
        ),
    ]
