# Generated by Django 3.0.6 on 2020-07-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0011_auto_20200703_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nativelanguage',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='nativelanguage',
            name='level',
        ),
        migrations.RemoveField(
            model_name='nativelanguage',
            name='user',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='lang_name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='LanguageLevel',
        ),
        migrations.DeleteModel(
            name='NativeLanguage',
        ),
    ]
