# Generated by Django 3.0.6 on 2020-07-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0012_auto_20200703_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edit.Language'),
        ),
    ]
