# Generated by Django 3.0.6 on 2020-07-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0013_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edit.Language'),
        ),
    ]
