# Generated by Django 3.0.6 on 2020-07-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0018_auto_20200703_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
