# Generated by Django 3.0.6 on 2020-07-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0019_auto_20200704_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
