# Generated by Django 3.0.6 on 2020-07-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0021_auto_20200704_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
