# Generated by Django 3.0.6 on 2020-07-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0028_reply_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='commentsNum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyNum',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
