# Generated by Django 3.0.6 on 2020-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0029_auto_20200709_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='commentsNum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replyNum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
