# Generated by Django 3.0.6 on 2020-07-10 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edit', '0030_auto_20200709_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='originProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edit.Profile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='originUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='targetUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
