# Generated by Django 3.0.6 on 2020-07-10 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0031_auto_20200710_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_reply_like',
        ),
        migrations.AlterField(
            model_name='notification',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edit.Article'),
        ),
    ]
