# Generated by Django 3.0.6 on 2020-07-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0032_auto_20200710_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
