# Generated by Django 3.0.6 on 2020-07-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit', '0033_profile_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='JaEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=63)),
                ('mean', models.CharField(max_length=511)),
            ],
        ),
    ]
